name: image and version test
on:
  push:
    branches: base-ope-image
jobs:
  image-version-check:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          #pip install -r requirements.txt    
          pip install jupyter-book matplotlib numpy pandas jq
      - name: make build # makes the container image build 
        run: |
          #IMAGE=quay.io/rh_ee_keli/ucsls:stable-base-ope-latest
          #docker pull $IMAGE
          #docker image ls
          make build
      - name: get base image and version
        run: |
          IMAGE=quay.io/rh_ee_keli/ucsls:stable-base-ope-latest
          docker run -d --name stable $IMAGE 
          ID=$( docker ps -aqf "name=stable" )     
          docker inspect $IMAGE > image.json
          REPO_TAG=$(jq -r '.[0].RepoTags[0]' image.json)

          if [[ "$REPO_TAG" == "$IMAGE" ]]; then
                echo "CORRECT IMAGE AND VERSION"
          else
                echo "INCORRECT IMAGE or VERSION, $REPO_TAG is not the proper image $IMAGE"
                exit -1
          fi
