name: jupnb import check
on:
  push:
    branches: 
      - base-ope-image
jobs:
  jupnb-import-check:
    runs-on: ubuntu-latest # use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2 # use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install jupyter-book matplotlib numpy pandas ipywidgets notebook nbconvert p2j jupyterlab nbclient
      - name: Run Docker container
        run: |
          IMAGE=quay.io/rh_ee_keli/ope:beta-image-template-NERC-test
          #IMAGE=quay.io/rh_ee_keli/ucsls:stable-base-ope-latest
          docker run -d -p 8888:8888 --name mycontainer -v /test.ipynb:/home/jovyan/work $IMAGE #&& until docker exec mycontainer jupyter lab --version; do sleep 1; done
          container_id=$(docker ps -qf "name=mycontainer" | head -n 1)
          docker cp tests/test.ipynb $container_id:/home/jovyan/work
      - name: Wait for container to start
        run: |
          until docker exec mycontainer jupyter lab --version; do sleep 1; done
      - name: Execute Notebook
        run: |
          container_id=$(docker ps -qf "name=mycontainer" | head -n 1)
          echo $container_id
          docker exec $container_id jupyter lab --generate-config
          docker exec $container_id sh -c "echo 'c.NotebookApp.token = \"\"' >> /home/jovyan/.jupyter/jupyter_notebook_config.py"
          docker exec $container_id jupyter labextension install @jupyter-widgets/jupyterlab-manager #install widgets
          docker exec $container_id pip install nbclient
          docker exec $container_id jupyter lab build --minimize=False
          echo "running notebook"
          docker exec $container_id jupyter execute /home/jovyan/work/test.ipynb #if fails will exit here 
          echo "************SUCCESS***********"
      - name: Stop Docker container
        run: docker stop mycontainer
